# Apollo 配置（参考 copweb：bootstrap 提前注入 Environment）
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
apollo.bootstrap.namespaces=local,application
app.id=qCdREtShftb8BS5vlllIODvlTf7TNyMn
